### PR TITLE
Remove download links

### PR DESCRIPTION
**Pull request by bitboxer**

### CODE REVIEW

**Comment by moonglum** [comment]
I think the "Show on Github" Link makes sense, I would keep it 👍 Makes it easier to do PRs like this one right here. Removing the Download Links makes a lot of sense 👍

**Comment by code-later** [comment]
Agree with @moonglum on keeping "Show on GitHub"

**Comment by bitboxer** [comment]
Oh, sorry. Haven't seen that link in there. Will repair the PR now

**Comment by bitboxer** [comment]
PR updated.

**Comment by code-later** [comment]
Thanks @bitboxer

**Pull request merged**
